name: Deploy to prod

on:
  push:
    branches:
      - 'main'

env:
  VITE_API_ENDPOINT: ${{ vars.VITE_API_ENDPOINT }}
  VITE_OB_API_KEY: ${{ secrets.VITE_OB_API_KEY }}
  CDK_RECORD_PREFIX: ${{ vars.CDK_RECORD_PREFIX }}
  VITE_OB_CLIENT_ID: ${{ vars.VITE_OB_CLIENT_ID }}
  VITE_OB_DEFAULT_AGENT_CONFIG_PROFILE: ${{ vars.VITE_OB_DEFAULT_AGENT_CONFIG_PROFILE }}

  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY }}

  PROD_PIPELINE_EXECUTION_ROLE: ${{ vars.PROD_PIPELINE_EXECUTION_ROLE }}
  PROD_CLOUDFORMATION_EXECUTION_ROLE: ${{ vars.PROD_CLOUDFORMATION_EXECUTION_ROLE }}
  PROD_ARTIFACTS_BUCKET: ${{ vars.PROD_ARTIFACTS_BUCKET }}

  STACK_NAME: ${{ vars.STACK_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  APP_NAME: ${{ vars.APP_NAME }}
  CDK_DEFAULT_REGION: ${{ vars.CDK_DEFAULT_REGION }}

  CDK_ZONE: ${{ vars.CDK_ZONE }}
  CDK_CERTIFICATE_ARN: ${{ vars.CDK_CERTIFICATE_ARN }}
  CDK_DEFAULT_ACCOUNT: ${{ vars.CDK_DEFAULT_ACCOUNT }}
  CDK_PIPELINE_USER_ARN: ${{ vars.CDK_PIPELINE_USER_ARN }}

jobs:

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install all dependencies (both frontend and CDK)
      - name: Install dependencies
        run: npm install

      # Install AWS CDK CLI globally
      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      # Build the UI app
      - name: Build UI app
        run: npm run build
        env:
          CDK_RECORD_PREFIX: ${{ env.CDK_RECORD_PREFIX }}
          VITE_API_ENDPOINT: ${{ env.VITE_API_ENDPOINT }}
          VITE_OB_API_KEY: ${{ env.VITE_OB_API_KEY }}
          VITE_OB_CLIENT_ID: ${{ env.VITE_OB_CLIENT_ID }}
          VITE_OB_DEFAULT_AGENT_CONFIG_PROFILE: ${{ env.VITE_OB_DEFAULT_AGENT_CONFIG_PROFILE }}
          STACK_NAME: ${{ env.STACK_NAME }}

      # Assume the AWS role for deployment
      - name: Assume the prod pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.PROD_PIPELINE_EXECUTION_ROLE }}
          role-session-name: prod-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      # Deploy the AWS infrastructure using the cdk-deploy npm script
      - name: Deploy infrastructure with AWS CDK
        run: npm run cdk-deploy -- --require-approval never --all
        env:
          CDK_RECORD_PREFIX: ${{ env.CDK_RECORD_PREFIX }}
          VITE_API_ENDPOINT: ${{ env.VITE_API_ENDPOINT }}
          VITE_OB_API_KEY: ${{ env.VITE_OB_API_KEY }}
          VITE_OB_CLIENT_ID: ${{ env.VITE_OB_CLIENT_ID }}
          VITE_OB_DEFAULT_AGENT_CONFIG_PROFILE: ${{ env.VITE_OB_DEFAULT_AGENT_CONFIG_PROFILE }}
          STACK_NAME: ${{ env.STACK_NAME }}
